### ISSUE TITLE
v3.0: Slots

### ISSUE THREAD

**Issue by osipxd** [EndlessCodeGroup/RPGInventory#41]
## Base options

- [ ] Name (ID)
- [ ] Texture
- [ ] Slot type

List of slot types must be dynamically changeable from other plugins.
All slots must support placeholders in description nad name.

### Unlockable
Slots that can be unlocked 
- [ ] Money cost
- [ ] Required level
- [ ] Required class
- [ ] Required permission
- [ ] Slot replace when it isn't unlocked

### Container
Stlot that can contains items
- [ ] List of allowed and denied items
- [ ] Drop on death or not
- [ ] Duplicate to [id of slot in player inventory]

### Action
Slot that can be used as button
- [ ] On click
- [ ] On Right Click
- [ ] On Left Click

Actions: `WORKBECH`, `ENDERCHEST`, `COMMAND:<command_here>[:player|console]`, `GUI:<gui_name>`

**Comment by OsipXD** [comment]
## Slot types
_Generic_ - Slot without any functions (is this good name for this slot type? Variants: _Basic_, _Base_, _Common_, _Simple_)
_Passive_ - Slot for passive items
_Active_ - Slot for active items (weapons etc.)
_Action_ - Slot that can apply actions on click (maybe remove this type and just add `action` section to all slot types? Also this name so similar to _Active_, as variant use _Button_)

### Special slot types
_Armor_ - Slots for vanilla armor. (Or may be better to create separated types for each type of armor?)
_Shield_ - Slot for second hand (maybe rename to _Offhand_?)
_Elytra_ - Slot for elytra
_Pet_ - Slot for pet (merge this with MyPet maybe?)

### Removed
_Info_ - Because placeholders now can be read from any slot description.
_Backpack_ - Because can be implemented with _Generic_ slot and item with container.

**Comment by KnifeKat** [comment]
I think you should make the MyPET and PET slots merged to be quite honest. So we don't have to have two different slots if server owners decide they want to allow 2 pets at once. Would make it cleaner for sake of clarity, OR if we allow only one slot to be in the RPGInventory, we don't have to add a second one just to accommodate a MYPET. 

Shield Renamed to Offhand is MUCH better. Also, able to make the texture for it as if it was meant for an offhanded item? Instead of the shape of a shield? Maybe a Shield & Sword Crisscrossed or something. Seems silly to put a Sword in a slot that looks like a Shield.

Armor: What do you mean create separated types for each kind of armor? What would this do?

**SLOT TYPES:** 

**Action**: I think you should make an Action slot & add action to all slot types. So admins can make a action Slot to allow the use of a Command(That has a cooldown of how often it can be used), as well as whatever people would like to use the rest for.

**Generic**: This is fine for the name for a basic slot.

**- Enhancement:**  You mentioned this before, but this would be awesome, just to reiterate:

Slot for Arrows. Whatever arrow is equipped would be the default arrow that is used when a Bow is being used. Instead of it randomly picking an arrow while its in your inventory. This would be good for people carrying multiple types of arrows, and not having to worry about which arrow is being used. Would look really nice in the RPGInventory GUI too.

Possibly another slot type to be added is "Scrolls" instead of just "Artifacts". Since artifacts look like relics essentially, or broken pieces of old ancient items, while the current artifacts are depictions of ancient scrolls. 

Types to consider adding, based on a few MMORPGs I play:

Gems.
Scrolls.
Relics.
Talismans.


I'll edit and add to this as I think of things to come up with.

**Comment by OsipXD** [comment]
- **MyPet** and **Pet** merged
- **Action** removed
- **Generic** not renamed

Under "create separated types for each kind of armor" I mean create **Helmet**, **Chestplate**, **Leggings**, **Boots** instead of one slot type **Armor**
I think it will make config files and source code more clear.

About slot types Scrolls, Gems etc.
I think all of these can be realized with **Passive** slot type that now used for artifacts slots.

**Comment by KnifeKat** [comment]
Oh, yeah. Actually making different types of Armor Slots would be best, then. Like the Helmet, Chestplate etc. People that are new, would be easier for those people to make the slots easier in their config, too. Would make it very clear what slot is what slot. Makes it user-friendly as well. That is a great idea, honestly.

Yeah, the slot type for Artifacts and stuff could just be the Passive Slot. Since Passive seems to be more a universal slot than anything. Backpacks, Artifacts/gems/Talismans/Scrolls etc. I'd take out Runs/Amulets too and just allow all of those to be placed in the Passive slots. 

Removes all the different kinds of slots, and makes it a little more clear what they are used for. Passive could be used for Gloves, Artifacts, Arrows, Scrolls, Gems, Talismans, Amulets, Rings, etc. Only thing that might be weird is the texture you use for the passive slots to accommodate it being used for a huge assortment of items.
