### ISSUE TITLE
Ocelot Pet

### ISSUE THREAD

**Issue by doitliketyler** [EndlessCodeGroup/RPGInventory#67]
Currently, the Ocelot does not work as one of the default "pets" like a wolf or horse. Could you please fix that? I'd really like to make a cat pet. Thank you.

**Comment by KnifeKat** [comment]
You need to use MyPet, or MyPetPremium to get any pets beyond Horse/Wolf. Here is a link to that Plugin. 

Make sure the pet type is set to "MYPET" in Slots, in order to equip Mypet Eggs to the Egg slot.

https://www.spigotmc.org/resources/mypet.12725/

You have to make a Cat Pet from MyPet in game, then it'll become an Egg to equip into RPG Inventory. ^^ Hope that helps!

**Comment by doitliketyler** [comment]
That's not going to work for me. I use MyPet for donators to buy pets with and you can't have more than 1 MyPet active. Furthermore, an Ocelot is one of the default tameable mobs in Minecraft so it really doesn't make sense to not have them work in RPGInventory as one of the default pets like the wolf and horse.

**Comment by KnifeKat** [comment]
In an RPG aspect, a cat would never be used, vs a Dog for fighting and a
Horse for Riding.

Iirc, having a MYPET for people as perks would be a breach of the EULA
since it gives benefits beyond cosmetics to a player (ie riding or pets
that can attack that other players don't have access to.)

If that MYPET is not exclusively being there as a random dead AI pet that
mindlessly follows you around, it breaks the EULA.

(Aka there is no problem making cats in mypet. Since you're wanting it in
RPGinv im.assuming you want the cat to be able to function like a Dog in
the fact it'll have damage values in RPGinv,  just like the wolf.

On Sep 21, 2017 10:51 PM, "Tyler King" <notifications@github.com> wrote:

That's not going to work for me. I use MyPet for donators to buy pets with
and you can't have more than 1 MyPet active. Furthermore, an Ocelot is one
of the default tameable mobs in Minecraft so it really doesn't make sense
to not have them work in RPGInventory as one of the default pets like the
wolf and horse.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/EndlessCodeGroup/RPGInventory/issues/67#issuecomment-331343234>,
or mute the thread

**Comment by doitliketyler** [comment]
1. That is just your opinion and you are making assumptions on how I'm utilizing the pet feature. 

2. Again...you are making assumptions. I know all about the EULA and my MyPets are EULA friendly.

3. No, it won't because as I originally said you can only have 1 MyPet active at a time.

**Comment by OsipXD** [comment]
I'll add more pet types in v3.0 but not now
