### ISSUE TITLE
Weapon Slot Item Duplication

### ISSUE THREAD

**Issue by doitliketyler** [EndlessCodeGroup/RPGInventory#68]
In the hotbar if I place a weapon it picks up the custom texture item in its place. I can move the weapon out and it will reappear but as soon as I place the sword back it does it again. See here: https://imgur.com/a/jajjH

In the Equip menu if I unequip that weapon it duplicates it. See here: https://imgur.com/a/V3XeG

I'm running on Spigot 1.12.1 with the latest version of RPG Inventory. I also tested this on a fresh install as well and it still happens.

**Comment by doitliketyler** [comment]
Ok. I think I know why this is happening. Seems like you setup the plugin to take a diamond_hoe in those slots no matter what the durability settings are. I have over 400 custom item models using the Diamond Hoe which cannot be changed. Please adjust these slots to be specific to those specific durability settings you used in your texture pack.

**Comment by KnifeKat** [comment]
Texture pack doesn't modify the game at all. It only changes what the client views something as. So texture pack wouldn't be able to duplicate an item for you. If an item is duplicating, its due to something in the plugin or the game interaction with it.

**Comment by doitliketyler** [comment]
Yeah I know that and I didn't say it did either and from the looks of it you don't understand what I am saying in the first place. Please stop responding to my tickets. You are not the developer and you are not being helpful.

**Comment by KnifeKat** [comment]
If its a huge concern, the weapon slot can just be disabled. There isn't actually a need for the Weapon slot to begin with. Since all Slots are universal. So binding one of them to -only- hold weapons is kind of silly.

You are welcome for the mound of information. :)

You do realize, if you are using custom textures yourself...you can always CHANGE the diamond hoes to something else and apply the textures from the texture pack to another item. It doesn't HAVE to be a diamond_hoe that the plugin uses to apply the RPG Inventory Textures.

If you read the plugin information, you can just change the diamond_hoe to another item and modify the RPGInventory Texture pack accordingly.

You are welcome.

**Comment by doitliketyler** [comment]
I didn't say thanks. Bye now.

**Comment by OsipXD** [comment]
Ok, I'll create tool to generate resoulcepack with needed item.
